// Code generated by tools/generate_reexports.go. DO NOT EDIT.

package fibernative

import (
	"github.com/hiiamtin/goctxid"
)

// Re-exported constants from goctxid package for convenience
const (
	// DefaultHeaderKey is the default HTTP header key for correlation ID
	DefaultHeaderKey = goctxid.DefaultHeaderKey
)

// Re-exported generator functions from goctxid package for convenience
var (
	// DefaultGenerator is the default UUID v4 generator (cryptographically secure)
	DefaultGenerator = goctxid.DefaultGenerator

	// FastGenerator is a high-performance generator using atomic counter
	// ⚠️ WARNING: Exposes request count. Use only when performance is critical.
	FastGenerator = goctxid.FastGenerator
)

// NOTE: Context-based functions (FromContext, MustFromContext, NewContext) are NOT re-exported
// because fibernative stores correlation IDs in c.Locals(), not in context.Context.
//
// Use the fibernative-specific functions instead:
//   - FromLocals(c *fiber.Ctx) (string, bool)
//   - MustFromLocals(c *fiber.Ctx) string
//   - FromLocalsWithKey(c *fiber.Ctx, key string) (string, bool)
//   - MustFromLocalsWithKey(c *fiber.Ctx, key string) string
//
// If you need context-based storage for goroutine safety, use the adapters/fiber package instead.
