// Code generator for re-exporting goctxid functions in adapters
// This eliminates code duplication across all adapters
//
// Usage: go run tools/generate_reexports.go <adapter_name>
// Example: go run tools/generate_reexports.go fiber
package main

import (
	"fmt"
	"os"
	"text/template"
)

const reexportTemplate = `// Code generated by tools/generate_reexports.go. DO NOT EDIT.

package {{.Package}}

import (
	"context"

	"github.com/hiiamtin/goctxid"
)

// Re-exported constants from goctxid package for convenience
const (
	// DefaultHeaderKey is the default HTTP header key for correlation ID
	DefaultHeaderKey = goctxid.DefaultHeaderKey
)

// Re-exported generator functions from goctxid package for convenience
var (
	// DefaultGenerator is the default UUID v4 generator (cryptographically secure)
	DefaultGenerator = goctxid.DefaultGenerator

	// FastGenerator is a high-performance generator using atomic counter
	// ⚠️ WARNING: Exposes request count. Use only when performance is critical.
	FastGenerator = goctxid.FastGenerator
)

// Re-exported functions from goctxid package for convenience
// This allows users to call goctxid_{{.Package}}.FromContext() instead of importing goctxid separately

// FromContext retrieves the correlation ID from the context.
// Returns the correlation ID and a boolean indicating if it was found.
func FromContext(ctx context.Context) (string, bool) {
	return goctxid.FromContext(ctx)
}

// MustFromContext retrieves the correlation ID from the context.
// Returns the correlation ID or an empty string if not found.
func MustFromContext(ctx context.Context) string {
	return goctxid.MustFromContext(ctx)
}

// NewContext creates a new context with the correlation ID.
func NewContext(ctx context.Context, correlationID string) context.Context {
	return goctxid.NewContext(ctx, correlationID)
}
`

const fibernativeTemplate = `// Code generated by tools/generate_reexports.go. DO NOT EDIT.

package fibernative

import (
	"github.com/hiiamtin/goctxid"
)

// Re-exported constants from goctxid package for convenience
const (
	// DefaultHeaderKey is the default HTTP header key for correlation ID
	DefaultHeaderKey = goctxid.DefaultHeaderKey
)

// Re-exported generator functions from goctxid package for convenience
var (
	// DefaultGenerator is the default UUID v4 generator (cryptographically secure)
	DefaultGenerator = goctxid.DefaultGenerator

	// FastGenerator is a high-performance generator using atomic counter
	// ⚠️ WARNING: Exposes request count. Use only when performance is critical.
	FastGenerator = goctxid.FastGenerator
)

// NOTE: Context-based functions (FromContext, MustFromContext, NewContext) are NOT re-exported
// because fibernative stores correlation IDs in c.Locals(), not in context.Context.
//
// Use the fibernative-specific functions instead:
//   - FromLocals(c *fiber.Ctx) (string, bool)
//   - MustFromLocals(c *fiber.Ctx) string
//   - FromLocalsWithKey(c *fiber.Ctx, key string) (string, bool)
//   - MustFromLocalsWithKey(c *fiber.Ctx, key string) string
//
// If you need context-based storage for goroutine safety, use the adapters/fiber package instead.
`

type TemplateData struct {
	Package string
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: go run generate_reexports.go <adapter_name>\n")
		fmt.Fprintf(os.Stderr, "Example: go run generate_reexports.go fiber\n")
		os.Exit(1)
	}

	packageName := os.Args[1]

	// Use special template for fibernative (no context functions)
	var templateStr string
	if packageName == "fibernative" {
		templateStr = fibernativeTemplate
	} else {
		templateStr = reexportTemplate
	}

	tmpl, err := template.New("reexport").Parse(templateStr)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	data := TemplateData{
		Package: packageName,
	}

	err = tmpl.Execute(os.Stdout, data)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}
}
